repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.9
    hooks:
      - id: isort
        args: [-m, "3", -tc]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
      - id: pydocstyle
        exclude: "docs|tests"
  - repo: https://github.com/econchick/interrogate
    rev: 1.2.0
    hooks:
      - id: interrogate
        args: [-v, -g, docs/_static]
        exclude: "docs|tests"
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v tests
        language: system
        types: [python]
        stages: [push]
